In [62]:
dis = distance_test_point_to_all_train_point(z, X)

In [63]:
dis = np.sort(dis)

In [64]:
dis

array([ 5, 50])

In [65]:
a = np.array([2,3,4,5,8,6,3,5,67,789])

In [69]:
a1 = np.sort(a)
a1

array([  2,   3,   3,   4,   5,   5,   6,   8,  67, 789])

In [73]:
a1[:2]

array([2, 3])

In [6]:
c = [(1,'a'), (2, 'b'), (3,'c')]

In [11]:
test_list = [(1, 'Rash', 21), (2, 'Varsha', 20), (3, 'Kil', 19)]

In [15]:
res = list(zip(*c))[1]

In [16]:
res

('a', 'b', 'c')

In [17]:
d = [2,2,2,2,2,2,3,4,5,3,3]

In [19]:
max(set(d), key = d.count)

2

In [51]:
import numpy as np
from sklearn import neighbors, datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


def distance_point_to_point(test_point, train_point):
    d = test_point - train_point.reshape(test_point.shape)
    return np.sum(d*d)


def distance_test_point_to_all_train_point(test_point, train_point_matrix):
    X2 = np.sum(train_point_matrix*train_point_matrix, 1)
    z2 = np.sum(test_point*test_point)
    return X2 + z2 - 2*train_point_matrix.dot(test_point)


def get_k_nearest_neighbors(distances_array, k):
    sorted = np.sort(distances_array)
    return sorted[:k]


def weight(distances):
    sigma2 = 0.5
    return np.exp(-distances ** 2 / sigma2)


def k_nearest_neighbors(train_set, train_label, test_set, k):
    result = []
    for test_point in test_set:
        distances = distance_test_point_to_all_train_point(test_point, train_set)
        weight_distances = distances
        trained = sorted(list(tuple(zip(weight_distances, train_label))), key=lambda x: x[0])
        k_nearest_point = trained[:k]
        label = list(zip(*k_nearest_point))[1]
        result.append(max(set(label), key = label.count))
    return np.array(result)

In [52]:
iris = datasets.load_iris()
iris_x = iris.data
iris_y = iris.target

In [53]:
x_train, x_test, y_train, y_test = train_test_split(iris_x, iris_y, test_size=50)

In [54]:
y_pred = k_nearest_neighbors(train_set=x_train, train_label=y_train, test_set=x_test, k=10)

In [56]:
print(y_pred)
print(y_test)
print(100 * accuracy_score(y_test, y_pred))

[1 0 0 2 2 0 2 2 0 2 2 1 1 0 2 1 2 2 1 0 2 1 2 1 0 0 1 1 1 0 0 1 2 0 2 2 1
 1 2 0 2 0 0 1 2 1 2 2 0 2]
[1 0 0 2 2 0 2 2 0 2 2 1 1 0 2 1 2 2 1 0 2 1 2 1 0 0 1 1 1 0 0 1 2 0 2 2 1
 1 2 0 2 0 0 1 2 2 2 2 0 2]
98.0


### K-mean clustering

In [2]:
import numpy as np
import scipy

#### function

In [36]:
def kmean_init_centroid(X, k):
    K = X[np.random.choice(X.shape[0], k, replace=False)]
    return K

In [31]:
X = np.array([[1,2],[3,4],[5,6],[7,8]])

In [27]:
np.argmin(X, axis=1)

array([0, 0, 0, 0])

In [19]:
k = np.random.choice(X.shape[0],2, replace=False)

In [25]:
kmean_init_centroid(X,2)

array([[5, 6],
       [1, 2]])

In [55]:
def kmean_assign_label(X, centroids):
    distances = scipy.spatial.distance.cdist(X, centroids)
    return np.argmin(distances, axis=1)

In [47]:
def kmean_update_centroids(X, label, K):
    centroid = np.zeros((K, X.shape[1]))
    for k in range(K):
        Xk = X[label==k,:]
        centroid[k,:] = np.mean(Xk)
    return centroid

In [48]:
def has_converged(centroid, new_centroid):
    return (set([tuple(a) for a in centroid])) == (set([tuple(a) for a in new_centroid]))

In [33]:
np.zeros((3, X.shape[1]))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [60]:
def kmeans(X, K):
    centroids = [kmean_init_centroid(X, K)]
    labels = []
    it = 0
    while True:
        labels.append(kmean_assign_label(X, centroids[-1]))
        new_centroids = kmean_update_centroids(X, labels[-1], K)
        if has_converged(new_centroids, centroids[-1]):
            break
        centroids.append(new_centroids)
        it+=1
    return centroids, labels, it

In [61]:
means = [[2,2], [8,3], [3,6]]
cov = [[1,0],[0,1]]
N= 500
X0 = np.random.multivariate_normal(means[0], cov, N)
X1 = np.random.multivariate_normal(means[1], cov, N)
X2 = np.random.multivariate_normal(means[2], cov, N)

X = np.concatenate((X0, X1, X2), axis=0)
K=3
original_label = np.asarray([0]*N + [1]*N + [2]*N).T

In [62]:
kmean_init_centroid(X, K)

array([[7.98677091, 1.32024807],
       [1.36770361, 5.71650057],
       [9.60890989, 2.8145787 ]])

In [63]:
centroids, labels, it = kmeans(X, K)

In [65]:
centroids[-1]

array([[1.94440105, 1.94440105],
       [5.73218325, 5.73218325],
       [4.39782776, 4.39782776]])

In [ ]:
# viết chương trình phân loại chữ viết tay sử dụng thuật toán k-means. dùng thư viên sklearn để thực hiện.
# bộ dữ liệu training là bộ dữ liệu MNIST.