In [1]:
import numpy as np

In [2]:
d, N = 1000, 10000

In [3]:
d

1000

In [4]:
N

10000

In [5]:
X = np.random.rand(N, 5)

In [6]:
X

array([[0.5903654 , 0.58185458, 0.27269209, 0.31061416, 0.83574055],
       [0.20351405, 0.52633443, 0.8053818 , 0.23244708, 0.61777001],
       [0.35759611, 0.66598159, 0.80557469, 0.2207136 , 0.26300984],
       ...,
       [0.3783147 , 0.02958715, 0.49867396, 0.85535848, 0.87648051],
       [0.58619613, 0.31461922, 0.67678391, 0.54658291, 0.52596125],
       [0.34846461, 0.26364028, 0.98728738, 0.62161558, 0.73165264]])

In [7]:
test_point = np.array([1,2,3,4,5])
train_point = np.array([4,5,6,7,8])

In [10]:
def distance_point_to_point(test_point, train_point):
    d = test_point - train_point.reshape(test_point.shape)
    return np.sum(d*d)

In [11]:
distance_point_to_point(test_point, train_point)

(45, array([-3, -3, -3, -3, -3]))

In [47]:
X = np.array([[1,2,3], [4,5,6]])

In [48]:
z = np.array([1,1,1])

In [61]:
def distance_test_point_to_all_train_point(test_point, train_point_matrix):
    X2 = np.sum(train_point_matrix*train_point_matrix, 1)
    z2 = np.sum(test_point*test_point)
    return X2 + z2 - 2*train_point_matrix.dot(test_point)

In [62]:
dis = distance_test_point_to_all_train_point(z, X)

In [63]:
dis = np.sort(dis)

In [64]:
dis

array([ 5, 50])

In [65]:
a = np.array([2,3,4,5,8,6,3,5,67,789])

In [69]:
a1 = np.sort(a)
a1

array([  2,   3,   3,   4,   5,   5,   6,   8,  67, 789])

In [73]:
a1[:2]

array([2, 3])

In [6]:
c = [(1,'a'), (2, 'b'), (3,'c')]

In [11]:
test_list = [(1, 'Rash', 21), (2, 'Varsha', 20), (3, 'Kil', 19)]

In [15]:
res = list(zip(*c))[1]

In [16]:
res

('a', 'b', 'c')

In [17]:
d = [2,2,2,2,2,2,3,4,5,3,3]

In [19]:
max(set(d), key = d.count)

2

In [51]:
import numpy as np
from sklearn import neighbors, datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


def distance_point_to_point(test_point, train_point):
    d = test_point - train_point.reshape(test_point.shape)
    return np.sum(d*d)


def distance_test_point_to_all_train_point(test_point, train_point_matrix):
    X2 = np.sum(train_point_matrix*train_point_matrix, 1)
    z2 = np.sum(test_point*test_point)
    return X2 + z2 - 2*train_point_matrix.dot(test_point)


def get_k_nearest_neighbors(distances_array, k):
    sorted = np.sort(distances_array)
    return sorted[:k]


def weight(distances):
    sigma2 = 0.5
    return np.exp(-distances ** 2 / sigma2)


def k_nearest_neighbors(train_set, train_label, test_set, k):
    result = []
    for test_point in test_set:
        distances = distance_test_point_to_all_train_point(test_point, train_set)
        weight_distances = distances
        trained = sorted(list(tuple(zip(weight_distances, train_label))), key=lambda x: x[0])
        k_nearest_point = trained[:k]
        label = list(zip(*k_nearest_point))[1]
        result.append(max(set(label), key = label.count))
    return np.array(result)

In [52]:
iris = datasets.load_iris()
iris_x = iris.data
iris_y = iris.target

In [53]:
x_train, x_test, y_train, y_test = train_test_split(iris_x, iris_y, test_size=50)

In [54]:
y_pred = k_nearest_neighbors(train_set=x_train, train_label=y_train, test_set=x_test, k=10)

In [56]:
print(y_pred)
print(y_test)
print(100 * accuracy_score(y_test, y_pred))

[1 0 0 2 2 0 2 2 0 2 2 1 1 0 2 1 2 2 1 0 2 1 2 1 0 0 1 1 1 0 0 1 2 0 2 2 1
 1 2 0 2 0 0 1 2 1 2 2 0 2]
[1 0 0 2 2 0 2 2 0 2 2 1 1 0 2 1 2 2 1 0 2 1 2 1 0 0 1 1 1 0 0 1 2 0 2 2 1
 1 2 0 2 0 0 1 2 2 2 2 0 2]
98.0
